### ISSUE TITLE
POST with simple parameter or JSON parameters ?

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/documentation#3]
A POST request body can be either a GET-like parameter list :
```
studyPUI=http://phenome.fr/maugio/2456
&studyPUI=http://phenome.fr/maugio/246
```
OR a json object :
```json
{
  "studyPUI":[
    "http://phenome.fr/maugio/2456",
    "http://phenome.fr/maugio/246"
  ]
}
```

**Comment by jeback1** [comment]
Although I'm not the best person to comment on this since I am not implementing the services myself, my belief is that the simple parameter approach would be easier to implement and would thus be the better choice for Version 1 of the API. To those doing actual implementations: please contradict me if you disagree!

An example of another system's approach to a similar problem: for a list of parameters with the same key, BioMart separates them with a bar. In the following example, the items in the list of ATTRIBUTES are separated with bars:
http://phytozome.jgi.doe.gov/biomart/martview?VIRTUALSCHEMANAME=zome_mart&ATTRIBUTES=phytozome.default.features.gene_name1|phytozome.default.features.transcript_name1|phytozome.default.features.go_desc|phytozome.default.features.ko_id

Would it be simpler for a service implementor to parse:

?studyPUI=http://phenome.fr/maugio/2456&studyPUI=http://phenome.fr/maugio/246

or

?studyPUI=http://phenome.fr/maugio/2456|http://phenome.fr/maugio/246

**Comment by jackeblagare** [comment]
We're implementing POST data as JSON objects in the Breeding4Rice REST API. It may be more complicated but in my opinion, the advantages it can offer is worth it. In our case, we find the following an advantage when using JSON objects among other things:
+ Readability
+ No problems when parameter becomes too long.
+ Easier to manipulate if there are multiple records being passed.

**Comment by gcornut** [comment]
POST can be used to search resources with a JSON request body containing the parameters 
See [search studies call](http://docs.brapi.apiary.io/#reference/study/search-studies/search-studies)
See [search germplasm call](http://docs.brapi.apiary.io/#reference/germplasm/germplasm-search/germplasm-search-through-post)
See issue #9
