### ISSUE TITLE
POST search calls should be suffixed with "-search"

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/documentation#9]
Cases:
- germplasm-search
- study-search
- phenotype-search
- allematrix-search

**Comment by jeback1** [comment]
The original definition of germplasm and germplasm-mcpd calls:

## Germplasm Search [/brapi/v1/germplasm?name={name}&matchMethod={matchMethod}&include={synonyms}&pageSize={pageSize}&page={page}]
Scope: CORE.  Status: STABLE.
Implementation target date: PAG2016
Implemented by: Germinate, Flapjack, Tripal Brapi Client, Cassavabase

Other service requests use the server's internal `germplasmDbId`. This service returns germplasm records that provide the germplasmDbId.
For the requested name or synonym, returns an array (possibly empty) of germplasm records that match the search criteria.
- If there is none, an empty array is returned.  
- If there is one or more than one match, returns an array of all germplasm records that match the search criteria.

###### Response data types
|Variable|Datatype|Description|Required|  
|------|------|------|:-----:|
|metadata|object|pagination, status|Y|
|pagination|object|pageSize, currentPage, totalCount, totalPages|Y|
|status|list|code, message|Y|
|result|object|data|Y|
|data|array of objects|Array (possibly empty) of germplasm records|Y|
|germplasmDbId|string|Internal db identifier|Y|
|defaultDisplayName|string|A string representing the germplasm that will be meaningful to the user|Y|
|germplasmName|string|Name of the germplasm. It can be the prefered name and does not have to be unique||
|accessionNumber|string|This is the unique identifier for accessions within a genebank, and is assigned when a sample is entered into the genebank collection||
|germplasmPUI|string|Permanent identifier (e.g. URI, DOI, LSID)||
|pedigree|string|Cross name with optional selection history.||
|seedSource|string|Seed source||
|synonyms|array of string|List of other names for this germplasm||


### Search names to retrieve germplasm records [GET]
+ Parameters
    + name (optional, text, `morex mor% mo* mo?ex`) ... The name or synonym.
    + matchMethod (optional, string, `wildcard`) ... Possible values are 'case_insensitive', 'exact' (case sensitive), 'wildcard' 
    (which is case insensitive). Wildcard uses both '*' and '%' for any number of characters and '?' for one-character matching. 
    Default is exact. Note: for implementation be aware that security issues (e.g. sql injection) are the responsibility of the developer.
    + include (optional, string, `synonyms`) ... Whether to include synonyms in the output.
    + pageSize (optional, integer, `1000`) ... The size of the pages to be returned. Default is `1000`.
    + page (optional, integer, `10`) ... Which result page is requested
+ Response 200 (application/json)

        {    
            "metadata": {
                "pagination": {
                    "pageSize": 1000,
                    "currentPage": 10,
                    "totalCount": 27338,
                    "totalPages": 28
                },
                "status": [],
                "datafiles": []
            },
            "result" : { 
                "data": [
                    { 
                        "germplasmDbId": "382",
                        "defaultDisplayName": "Pahang",
                        "germplasmName": "Pahang",
                        "accessionNumber": "ITC0609",
                        "germplasmPUI": "http://www.crop-diversity.org/mgis/accession/01BEL084609",
                        "pedigree": "TOBA97/SW90.1057",
                        "seedSource": "",
                        "synonyms": ["01BEL084609"],
                    },
                    {
                        "germplasmDbId": "394",
                        "defaultDisplayName": "Pahang",
                        "germplasmName": "Pahang",
                        "accessionNumber": "ITC0727",
                        "germplasmPUI": "http://www.crop-diversity.org/mgis/accession/01BEL084727",
                        "pedigree": "TOBA97/SW90.1057",
                        "seedSource": "",
                        "synonyms": [ "01BEL084727"],
                    }
                ]
            }
        }    



##  Germplasm MCPD Search [/brapi/v1/germplasm-search?germplasmName=&germplasmGenus=&germplasmSubTaxa=&germplasmDbId&germplasmPUI=http://data.inra.fr/accession/234Col342&germplasmSpecies=Triticum&panel=diversitypanel1&collection=none&pageSize=pageSize&page=page]
Scope: CORE. Status: IN DISCUSSION.  
Implementation target date: PAG2017
Implemented by: GnpIS

Adresses two needs : 
1. possibility to search germplams by more parameters than those alowed by the existing germplasm search
2. possibility to get MCPD details by PUID rather than dbId

###### Response data types
|Variable|Datatype|Description|Required|  
|------|------|------|:-----:|
|metadata|object|pagination, status|Y|
|pagination|object|pageSize, currentPage, totalCount, totalPages|Y|
|status|list|code, message|Y|
|result|object|Object containing MCPD data|Y|
|germplasmDbId|string|Internal db identifier|Y|
|defaultDisplayName|string|A string that can be displayed to the user|Y|
|accessionNumber|string|This is the unique identifier for accessions within a genebank, and is assigned when a sample is entered into the genebank collection||
|germplasmName|string|Name of the germplasm. It can be the prefered name and does not have to be unique||
|germplasmPUI|string|Permanent identifier (e.g. URI, DOI, LSID)||
|pedigree|string|Cross name with optional selection history.||
|seedSource|string|Seed source||
|synonyms|array of string|List of other germplasm name||
|commonCropName|string|Common name fo the crop (e.g. wheat, rice, maize, cassava, banana)||
|instituteCode|string|Institute that has bred the material. Note: The code may consist of the 3-letter ISO 3166 country code of the country where the institute is located plus a number (e.g. COL001) as recommended by FAO WIEWS |Y|
|instituteName|string|Name of the institute (or person) that bred the material.||
|biologicalStatusOfAccessionCode|string|400) Breeding/research material 410) Breeder's line 411) Synthetic population 412) Hybrid 413) Founder stock/base population 414) Inbred line (parent of hybrid cultivar) 415) Segregating population 416) Clonal selection 420) Genetic stock 421) Mutant (e.g. induced/insertion mutants, tilling populations) 422) Cytogenetic stocks  423) Other genetic stocks (e.g. mapping populations)500) Advanced or improved cultivar (conventional breeding methods) 600) GMO (by genetic engineering) 999) Other||
|countryOfOriginCode|string|3-letter ISO 3166-1 code of the country in which the sample was bred or selected (breeding lines, GMOs, segregating populations, hybrids, modern cultivars, etc.).||
|typeOfGermplasmStorageCode|array of string|If germplasm is maintained under different types of storage, multiple choices are allowed. 10) Seed collection 11) Short term 12) Medium term 13) Long term 20) Field collection 30) In vitro collection 40) Cryopreserved collection 50) DNA collection 99) Other (elaborate in REMARKS field)||
|genus|string|Genus name for taxon. Initial uppercase letter required.||
|species|string|Specific epithet portion of the scientific name in lowercase letters.||
|speciesAuthority|string|||
|subtaxa|string|Subtaxon can be used to store any additional taxonomic identifier. The following abbreviations are allowed: ‘subsp.’ (for subspecies); ‘convar.’ (for convariety); ‘var.’ (for variety); ‘f.’ (for form); ‘Group’ (for ‘cultivar group’).|
|subtaxaAuthority|string|||
|donors|array of object|code of the donor institute and Identifier assigned to an accession by the donor, and permanent identifier.||
|acquisitionDate|string|Date on which the accession entered the collection where YYYY is the year, MM is the month and DD is the day. Missing data (MM or DD) should be indicated with hyphens or ‘00’ [double zero].|

### Germplasm MCPD search [POST]
+ Parameters
    + germplasmPUI (optional, text, `http://data.inra.fr/accession/234Col342`) ... The name or synonym of external genebank accession identifier
    + germplasmDbId (optional, text, `986`) ... The name or synonym of external genebank accession identifier
    + germplasmSpecies (optional, text, `aestivum`) ... The name or synonym of genus or species ( merge with below ?)
    + germplasmGenus (optional, text, `Triticum, Hordeum`) ... The name or synonym of genus or species
    + germplasmName (optional, text, `Triticum, Hordeum`) ... The name or synonym of the accession
    + germplasmSubTaxa (optional, text, `cv. Charger, subsp. aestivum`) ... The name or synonym of MCPD subTaxa. Exact Match, abreviations must be MCPD compliant (‘subsp.’ for 'subspecies'; ‘convar.’ for "convariety" ‘var.’ for variety; ‘f.’ for 'form'; ‘Group’ for ‘cultivar group’)
    + panel (optional, text, `breedingProgramPanel2011`) ... The name of a specific panel 
    + collection (optional, text, `BRCCollection_Wheat`) ... The name of a specific Collection    
    + pageSize (optional, integer, `1000`) ... The size of the pages to be returned. Default is `1000`.
    + page (optional, integer, `10`) ... Which result page is requested
 
+ Response 200 (application/json)

        {
            "metadata": {
                "status": [],
                "datafiles": [],
                "pagination": {
                "pageSize": 10,
                "currentPage": 1,
                "totalCount": 2,
                "totalPages": 1
                }
            },
            "result": {
                "data":[
                    {
                        "germplasmDbId": "01BEL084609",
                        "defaultDisplayName": "Pahang",
                        "accessionNumber": "ITC0609",
                        "germplasmName": "Pahang",
                        "germplasmPUI": "http://www.crop-diversity.org/mgis/accession/01BEL084609",
                        "pedigree": "TOBA97/SW90.1057",
                        "germplasmSeedSource": "Female GID:4/Male GID:4",
                        "synonyms": [ ],
                        "commonCropName": "banana",
                        "instituteCode": "01BEL084",
                        "instituteName": "ITC",
                        "biologicalStatusOfAccessionCode": 412,
                        "countryOfOriginCode": "UNK",
                        "typeOfGermplasmStorageCode": 10,
                        "genus": "Musa",
                        "species": "acuminata",
                        "speciesAuthority": "",
                        "subtaxa": "sp malaccensis var pahang",
                        "subtaxaAuthority": "",
                        "donors": 
                        [
                            {
                                "donorAccessionNumber": "",
                                "donorInstituteCode": "",
                                "germplasmPUI": ""
                            }
                        ],
                        "acquisitionDate": "19470131"
                    ,{
                        "germplasmDbId": "03REL084609",
                        "defaultDisplayName": "Pah",
                        "accessionNumber": "ITC0685",
                        "germplasmName": "Pah",
                        "germplasmPUI": "doi:10.15454/328757862534E12",
                        "pedigree": "TOBA97/SW90.1057",
                        "germplasmSeedSource": "Female GID:4/Male GID:4",
                        "synonyms": [ ],
                        "commonCropName": "banana",
                        "instituteCode": "01BEL084",
                        "instituteName": "ITC",
                        "biologicalStatusOfAccessionCode": 412,
                        "countryOfOriginCode": "UNK",
                        "typeOfGermplasmStorageCode": 10,
                        "genus": "Musa",
                        "species": "acuminata",
                        "speciesAuthority": "",
                        "subtaxa": "sp malaccensis var pah",
                        "subtaxaAuthority": "",
                        "donors": 
                        [
                            {
                                "donorAccessionNumber": "",
                                "donorInstituteCode": "",
                                "germplasmPUI": ""
                            }
                        ],
                        "acquisitionDate": "19770131"
                    }
                ]
            }
        }
